# Generated by Django 3.1.2 on 2020-10-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=75)),
                ('fono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=75)),
                ('masa', models.CharField(max_length=75)),
                ('salsa', models.CharField(max_length=75)),
                ('queso', models.CharField(max_length=75)),
                ('ingrediente1', models.CharField(max_length=75)),
                ('ingrediente2', models.CharField(max_length=75)),
                ('ingrediente3', models.CharField(max_length=75)),
                ('bebida', models.CharField(max_length=75)),
                ('observacion', models.CharField(max_length=75)),
            ],
        ),
    ]
